name: ssafytime
description: app for ssafy people

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  percent_indicator: ^4.2.2
  carousel_slider: ^4.2.1
  flutter_secure_storage: ^7.0.1
  http: ^0.13.5
  shared_preferences: ^2.0.17
  intl: ^0.17.0
  ntp: ^2.0.0
  expandable: ^5.0.1
  flutter_time_picker_spinner: ^2.0.0
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.17
  flutter_animation_progress_bar: ^2.3.1
  fluttertoast: 8.0.5
  double_back_to_close_app: ^2.1.0

  flutter_webrtc: ^0.9.21
  html: ^0.15.1

  # Custom flutter_survey (https://github.com/Michelphoenix98/flutter_survey)
  diffutil_sliverlist: ^0.5.1
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  flutter_spinkit: ^5.1.0

  # flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/no_menu.png
    - assets/image/no_week_menu.png
    - assets/image/no_profile_image.png
    - assets/image/ssafytime_Icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
